[tool.poetry]
name = "bgs-tool"
version = "0.1.20"
description = ""
authors = ["Luc Shelton <lucshelton@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/loveduckie/bgs-tool"
repository = "https://github.com/loveduckie/bgs-tool"
documentation = "https://github.com/loveduckie/bgs-tool/-/wikis/home"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
packages = [{ include = "bgs_tool/**/*" }, { include = "bgs_tool_tests/**/*" }]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pylint = "^3.2.5"

[tool.poetry.group.build.dependencies]
setuptools = "^75.6.0"
wheel = "^0.45.1"
twine = "^6.0.1"

[tool.poetry.scripts]
bgs-tool = 'bgs_tool.__main__:main'

[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.poetry.group.test.dependencies]
coverage = "^7.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry_bumpversion.file."bgs_tool/__init__.py"]
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
